dependencies {
  implementation 'io.projectreactor:reactor-core'
  implementation 'io.projectreactor.tools:blockhound'
}

sourceSets {
  main {
    java.srcDir 'src'
    resources.srcDir 'resources'
  }
  test {
    java.srcDir 'test'
  }
}

processResources {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}